sweetshop/final-project/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using final_project.Models;

namespace final_project.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult SignIn()
        {
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }
    }
}

sweetshop/final-project/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using final_project.Models;
using final_project.Data;
using Microsoft.AspNetCore.Http;

namespace final_project.Controllers
{
    public class UserController : Controller
    {
        private readonly RetrocordContext _context;

        public UserController(RetrocordContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            if (email == null || password == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Registration/SignIn");
            }

            var admin = _context.Admins.SingleOrDefault(u => u.Email == email && u.Password == password);

            if (admin == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Registration/SignIn");
            }

            HttpContext.Session.SetString("username", admin.Email);
            HttpContext.Session.SetString("fullName", admin.FullName);

            return RedirectToAction("Welcome", "Admin", null);
        }

        public IActionResult Logout()
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return View("Views/Users/NotFound.cshtml");
            }

            HttpContext.Session.Remove("username");
            return RedirectToAction("Index", "Home", null);
        }
    }
}

sweetshop/final-project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/disc.png">
    <title>Retrocord</title>

    <!--Load CSS-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="#">Retrocord - Admin Panel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Orders">Orders</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Costumers">Costumers</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Categories">Categories</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Branches">Branches</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Statistics">Statistics</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="EditProducts">Products</a>
                </div>
                <div class="float-right d-flex">
                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div>
        <div class="container view-container">

            @RenderBody()

        </div>
        <hr />
        <footer>
            <div class="row">
                <p class="col-md-6">&copy; 2020 - final project by Nirel Didi, Yael Haims, Tomer Hadad and Alon Kazimirsky</p>
                <div class="col-md-6">
                    <div id="fb-share-button">
                        <svg viewBox="0 0 12 12" preserveAspectRatio="xMidYMid meet">
                            <path class="svg-icon-path" d="M9.1,0.1V2H8C7.6,2,7.3,2.1,7.1,2.3C7,2.4,6.9,2.7,6.9,3v1.4H9L8.8,6.5H6.9V12H4.7V6.5H2.9V4.4h1.8V2.8 c0-0.9,0.3-1.6,0.7-2.1C6,0.2,6.6,0,7.5,0C8.2,0,8.7,0,9.1,0.1z"></path>
                        </svg>
                        <span>Share</span>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

sweetshop/final-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/disc.png">
    <title>Retrocord</title>

    <!--Load CSS-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/animate.css-master/animate.min.css">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <p class="navbar-title">Retrocord</p>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Shop">Shop</a>
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            </div>
        </div>
        <div class="float-right d-flex">
            <a class="" asp-area="" asp-controller="Registration" asp-action="SignIn">Sign In</a>
            <a asp-area="" asp-controller="Cart" asp-action="Cart">
                <i class="fa fa-shopping-cart fa-lg"></i>
            </a>
        </div>
    </nav>
    <div>
        @RenderBody()
        <footer>
            <div class="row layout-footer">
                <p class="col-10">&copy; 2020 - final project by Nirel Didi, Yael Haims, Tomer Hadad and Alon Kazimirsky</p>
                <div class="col-2">
                    <div id="fb-share-button">
                        <svg viewBox="0 0 12 12" preserveAspectRatio="xMidYMid meet">
                            <path class="svg-icon-path" d="M9.1,0.1V2H8C7.6,2,7.3,2.1,7.1,2.3C7,2.4,6.9,2.7,6.9,3v1.4H9L8.8,6.5H6.9V12H4.7V6.5H2.9V4.4h1.8V2.8 c0-0.9,0.3-1.6,0.7-2.1C6,0.2,6.6,0,7.5,0C8.2,0,8.7,0,9.1,0.1z"></path>
                        </svg>
                        <span>Share</span>
                    </div>
                </div>
            </div>
        </footer>
    </div>



    @RenderSection("Scripts", required: false)

    <script src="~/lib/WOW-master/dist/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>